# Generated by Django 4.1.7 on 2023-05-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="feed", name="profile_image",),
        migrations.RemoveField(model_name="feed", name="user_id",),
        migrations.AddField(
            model_name="feed",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
